{% set name = "lsdeluxe" %}
{% set version = "0.23.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Peltoche/lsd/archive/{{ version }}.tar.gz
  sha256: 9698919689178cc095f39dcb6a8a41ce32d5a1283e6fe62755e9a861232c307d

build:
  number: 0
  ignore_run_exports:
    - libstdcxx-ng

requirements:
  build:
    - {{ compiler('cxx') }}  # [linux]
    - {{ compiler('rust') }}
    - cargo-bundle-licenses

test:
  commands:
    - lsd --help

about:
  home: https://github.com/Peltoche/lsd
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: The next gen ls command
  dev_url: https://github.com/Peltoche/lsd

extra:
  recipe-maintainers:
    - m-rossi
