{% set name = "lsdeluxe" %}
{% set version = "0.23.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Peltoche/lsd/archive/{{ version }}.tar.gz
  sha256: 0ce6582745b5364fdb4052954d24f6a211af616061d1454583e68f3366f6496e

build:
  number: 0
  ignore_run_exports:
    - libstdcxx-ng

requirements:
  build:
    - {{ compiler('cxx') }}  # [linux]
    - {{ compiler('rust') }}
    - cargo-bundle-licenses

test:
  commands:
    - lsd --help

about:
  home: https://github.com/Peltoche/lsd
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: The next gen ls command
  dev_url: https://github.com/Peltoche/lsd

extra:
  recipe-maintainers:
    - m-rossi
