{% set name = "lsdeluxe" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Peltoche/lsd/archive/v{{ version }}.tar.gz
  sha256: 7933e196bf7b164ea8879078f8a8e87381e0c49f71867e0036c82916199aba61

build:
  number: 0
  ignore_run_exports:
    - libstdcxx-ng

requirements:
  build:
    - {{ compiler('cxx') }}  # [linux]
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  run:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  commands:
    - lsd --help

about:
  home: https://github.com/Peltoche/lsd
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: The next gen ls command
  dev_url: https://github.com/Peltoche/lsd

extra:
  recipe-maintainers:
    - m-rossi
