{% set name = "lsdeluxe" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Peltoche/lsd/archive/v{{ version }}.tar.gz
  sha256: ab34e9c85bc77cfa42b43bfb54414200433a37419f3b1947d0e8cfbb4b7a6325

build:
  number: 0
  ignore_run_exports:
    - libstdcxx-ng

requirements:
  build:
    - {{ compiler('cxx') }}  # [linux]
    - {{ compiler('rust') }}
    - cargo-bundle-licenses

test:
  commands:
    - lsd --help

about:
  home: https://github.com/Peltoche/lsd
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: The next gen ls command
  dev_url: https://github.com/Peltoche/lsd

extra:
  recipe-maintainers:
    - m-rossi
